### ISSUE TITLE
API Design: Vertices lifetime

### ISSUE THREAD

**Issue by DavidPeicho** [jbikker/tinybvh#33]
Hi!

The current version store the vertices slice in the following case:

```cpp
if (allocatedBVHNodes < spaceNeeded) {
    verts = (bvhvec4*)vertices;
}
```

This means that it's technically possible to read garbage from a previous `verts` pointer. While this is a fixable bug, the lifetime of `verts` could be a bit improved since it's not directly clear from just the doc and the method declaration, that the vertices slice is kept around.

#### Pass Around Vertex Slice

Ideally, every function would just read the slice once, and not store it:

```cpp
void BVH::Build(const bvhvec4* vertices, const unsigned primCount);
void BVH::Refit(const bvhvec4* vertices, const BVHLayout layout, const unsigned nodeIdx);
...
```

Makes it clear that `vertices` isn't bound to the bvh lifetime. It doesn't prevent user errors obviously:

```cpp
bvh.Build(triangles, 36);
bvh.Refit(otherTriangles, 36); // Oops
```

This will be the case with the current solution as well.

#### SetVertices

Another solution could be to explicitly ask for the vertices?

```cpp
void BVH::SetVertices(const bvhvec4* vertices, const unsigned primCount);

void BVH::Build() {
    FATAL_ERROR_IF(!verts, "BVH::Build(), no vertices (use SetVertices(vertices))" );
}
```

Let me know what you think, happy to contribute based on your preferences

**Comment by jbikker** [comment]
The current approach is indeed not as safe as can be.
An intermediate solution would be to move the verts assignment outside the if statement, so that the pointer is refreshed even when there is enough space.
The solution of sending verts to each function, as you propose, is much safer still - but that also means that Intersect and IsOccluded needs to receive this data, from a point in user code where it may be quite inconvenient to obtain a verts pointer, which may perhaps lead to a different but similar copy of the verts pointer.
Another solution would be to actually copy the data pointed to by verts. Performance-wise this is not a huge issue - although it is of course wasteful, also in terms of memory use.
Or, we could have additional checks on the verts pointer and the data it points to but only in debug mode. Perhaps with a CRC32 over the data?

**Comment by DavidPeicho** [comment]
Copying to me is a bit much. I guess the best solution then is to keep the assignment out of the if, and add some information in the `Build()` doc that `verts` must lived throughout the entire usage of `bvh`, until `Build` is called again.

**Comment by jbikker** [comment]
OK. For 1.0.5 the assignment is outside the if. Documentation is at the top of the priorities list, but you know how that goes... ;) At least every builder already has a comment there that says that you shouldn't delete the data.

**Comment by DavidPeicho** [comment]
@jbikker Would you be okay if I add a set of overloads to pass the vertices? I am asking because if I don't, it becomes impossible in Rust for the user to modify the original `triangles` list (since there is an immutable borrow in this library).

There are ways to circumvent that in Rust, but they aren't all amazing. I think if I could just pass the `vertices` slice when needed to tinybvh, would fix most of my issues.

**Comment by jbikker** [comment]
This would be alternative access to Intersect and such? I am a bit
reluctant because a larger api will also be harder to maintain, but I don't
want to obstruct your Rust initiative either.

- Jacco.

**Comment by DavidPeicho** [comment]
Actually just found a super elegant way to do it without changing anything in this library :) I hope I can release tomorrow!

**Comment by jbikker** [comment]
That's great! Looking forward to it.
