### ISSUE TITLE
API idea: Separate BVH/Layout from Convert()

### ISSUE THREAD

**Issue by DavidPeicho** [jbikker/tinybvh#41]
Yet another API discussion :D

It would have been awesome to separate the conversion from the `BVH` type itself, in pseudocode:

```cpp
/* In this case, we could probably skip the layout in the ctor, and just reset it to `WALD_32BYTE` on build */
BVH wald32{BVHLayout::WALD_32BYTE};
wald32.Build(triangles, primCount);

BVH cwbvh{BVHLayout::CWBVH};

/* Converts wald32 into cwbvh */
const bool success = tinybvh::convert(wald32, cwbvh);
```

The advantage would be:
* RAII to automatically delete unused bvh layout, memory management is simpler in general
* API feels a little more ergonomic (probably subjective), since it's quite clear that you can only obtain a `WALD32` bvh by building, and the other by converting

In terms of implementation, each BVH could be a union of each layout.

Not sure what you think about that, let me know :)

**Comment by jbikker** [comment]
Hm I see what you mean: Each BVH has one type at a time, and a convert produces or requires a new BVH.
Some considerations:
* Some BVHs may need reconstruction each frame. If this includes a convert, you now need to track / own both BVHs.
* It will be possible to directly build to BVH4/BVH8 later, perhaps also other formats. That doesn't appear to be a problem with this idea.
* Layouts will come and go. Not all of them make sense; e.g. when the WiVe traversal algo is done, Afra can be dropped. Also not a problem with this idea, just mentioning it.

Let's give it some thought.

**Comment by DavidPeicho** [comment]
* I think for the first point that's already the case, if you re-build/re-fit, you need to re-convert?
* I think a `BuildBVH4()` is perfect for that yes
* That part is a little tricky yes 🤔

**Comment by jbikker** [comment]
if you re-build/re-fit, you need to re-convert:
Yes, but if both the WALD_32BYTE and BVH_SOA (for example) are in the same BVH, your scene graph objects will have 1 BVH which you refit, then re-convert. In your proposed scenario each object would have two BVHs, one for each type, right?

**Comment by DavidPeicho** [comment]
Yes you would have to create 2 bvhs indeed. I mean, the current version also have "2" bvh (layouts), it's just implicit.

There is probably a better ideas out there for the design, trying to think of the use case. Personally I wouldn't mind having two since I will have one CPU BVH to handle refit/ fast build, and a GPU one for the pathtracing kernel, and the gpu one doesn't really need to relate to the CPU one after a conversion occurs.

There are probably a lot of use cases I also don't have on the top of my mind :D

**Comment by jbikker** [comment]
Slept a night on it. I think you're right, there is an opportunity here to significantly simplify the overall design.
I came up with this:
* A BVH class, which encapsulates 'only' the current WALD_32BYTE version: The builders, nodes in the WALD_32BYTE format, and intersection of WALD_32BYTE data.
* A BVH_Verbose class, who's only constructor takes a 'default' BVH. This class has methods like Optimize.
* Several other BVH classes, such as BVH_AILALAINE and BVH_SOA, all with constructors that require an existing 'default' BVH.
* Special case: BVH4 and BVH8, which again need a default BVH to be constructed, but which can in turn be used to construct 4-wide special-purpose BVHs, such as CWBVH.

Each of these classes is a regular C++ class, no template, no 'layout' identifier.
I thought about using BVH as a base class, but I see no real purpose in class derivation: the amount of shared data and methods is minimal, and frankly, you don't want two BVHs in a scene graph object: You want a BVH and a BVH_SOA, which is far more clear. This also avoids virtual function tables.

'Convert' completely disappears this way; it's contents are moved to the various constructors.

Intersect and IsOccluded will be implemented for all (or most) of the classes.

What do you think?

**Comment by DavidPeicho** [comment]
I always prefer explicit to implicit, as well as strongly typed. I think what you came up with is really good and makes sense, since some layouts can't be optimized, other can be refitted, etc... So having different types also make it clear what type of BVH layout can undergo certain operations.

> I thought about using BVH as a base class, but I see no real purpose in class derivation

Agree yes 👍

Creating a "unified" api is also possible entirely on the user side. For instance you could just create you own `BVH` type with a union of all layouts etc... Similar to what the library is doing right now. So I am too afraid here.

> 'Convert' completely disappears this way; it's contents are moved to the various constructors.

That makes sense, I guess we still need an `Update(const BVHWald32& bvh)` for some of them in case you want to re-build without re-allocating? Seems like that would be useful.

Hopefully we also do that without holding the `BVHWald32` reference in other classes (like `BVH_Verbose`). But I think there wouldn't be a reason to hold it since `Intersect` and `IsOccluded` just need the vertices?

**Comment by jbikker** [comment]
Good question... The conversion is in progress and will (at least in
concept) be done tomorrow, see 'api' branch. Usage is similar, with minimal
impact on existing apps (or so it seems, I use 'fenster' for testing). The
lib is quite young; perhaps the switch can simply be made, with a pointer
to the repo that still has the old interface? Then again, 560 stars seems
to indicate quite some interest and thus maybe a significant install base..

**Comment by DavidPeicho** [comment]
Wow you started on that really fast 😄 Thanks!

Usage is similar, except when a conversion is required. I am always in favor of ditching old code, I just don't know how many people already seriously rely on it and except to be able to update without an API breakage.

Let me know if you need help on the task.

**Comment by jbikker** [comment]
I'm running into an interesting problem. In fenster I want to build a BVH_SoA to quickly trace rays. This format is constructed from the default type which has the builders:

````BVH bvh;
BVH_SoA bvh2;````
..
bvh.BuildAVX( triangles, verts / 3 );
bvh2.ConvertFrom( bvh );````

Now, bvh2 is using several pointers produced by the builders. So if I delete ````bvh````, ````bvh2```` becomes invalid. Not a problem, but it may be rather tempting to have ````BVH bvh```` on the stack in an init function, just to produce ````BVH_SoA bvh2````. And then, when it goes out of scope, ````bvh2```` starts causing crashes... I know that a reference counting pointer would solve the issue here, but... That would be the first time I would feel forced to use that. Any advice?

**Comment by DavidPeicho** [comment]
> reference

That relates to my original issue I opened with the vertices. I don't think the converted BVHs should store the data to the original one. I know it means the API must receives `const BVH& original` everywhere, but that's expected IMO.

What data is copied except the pointer to the vertices?

**Comment by jbikker** [comment]
I see what you mean. Forcing to use the original bvh later indeed forces an extended lifetime. It seems rather ugly though.. The main use case is Intersect, as you illustrated. It seems odd to pass both the converted BVH and the original one...

Perhaps it would be better to actually copy the data upon conversion? At least as default behavior, maybe with the option of a conscious override? Data copies are very cheap after all (in terms of CPU cycles).

**Comment by DavidPeicho** [comment]
I guess your original design was somewhat connected to the second option I gave above. Maybe there is an in-between solution.
If we figure out something, I can do the rewrite so you don't go through the pain a second time 😄

**Comment by DavidPeicho** [comment]
The more I think about it, the more I believe we should find a way to just get new data out of conversion:

```cpp
BVH8 bvh8;
{
    BVH bvh;
    bvh.Build();
    bvh8.ConvertFrom(bvh);
 }
```

So maybe you are right and at least `triIdx` should be copied. In the future if there is a refit per type, maybe `triIdx` will need to be sorted again differently?

**Comment by DavidPeicho** [comment]
I think I am starting to agree with you, and the solution could be that a sub BVH might be owning or not. That would mean that we provide both overloads:

```cpp
int CWBVH:Intersect(Ray& ray, BVH& original);
int CWBVH:Intersect(Ray& ray) {
    assert(triIdx != nullptr); // Not owned
}
```

In addition, if we really want to simplify life of people that just want a `CWBVH` or anything, we could also just do the conversion for them to avoid ending up with an error:

```cpp
bvhvec4 verts = ...;
BVH8_CWBVH cwbh{verts}; // Create a `BVH`, convert, and `std::move` what is needed
```

**Comment by jbikker** [comment]
That's a great idea! In many cases there is no need for the original BVH, in which case the last option is great.
And how about this option:
When e.g. a bvh4 is made based on the data in bvh, it would also be possible to record this in the original bvh, so when the bvh is destroyed, the pointers in the derived tree(s) are destroyed as well. This can then trigger an error message, educating the user. Combined with proper documentation, this would be pretty fail-safe and fast.

**Comment by DavidPeicho** [comment]
So if I sum it up, we want two code paths with:
* Creation of sub bvh and directly use `std::move`, `bvh` isn't kept around
* A case where we keep it around, for later re-build maybe?
    * What do we do here? Do we do what I originally said about having a bvh being owner or not with overloads?

**Comment by jbikker** [comment]
Yes indeed, common / only scenarios would be
1. 'create sub-bvh and destroy original', which is best covered by directly
constructing the desired type; original is created and disposed of as part
of the construction of the target type. This is clear and can be done
easily. API-wise it's clear, since to the user, the original never exists.
2. create original, then: loop { convert to sub-bvh; update original; }.
There are extreme cases here, e.g. CWBVH, which goes from bvh2 to bvh8 to
cwbvh...

Regarding my previous idea: it gets weird indeed if multiple bvhs are
created from the same bvh, but the original could keep a vector of bvhs
that are created from it. Not pretty, but efficient (after all, it's a
mechanism that only exists to detect and prevent deletion), and transparent
to the user. The code for that could be copiously documented to explain why
that is done.

- Jacco.

**Comment by DavidPeicho** [comment]
In terms of concrete implementation, I was thinking of something along those lines:

```cpp
class BVH4View {
     void ConvertFrom(const BVH& bvh);
     int Intersect(Ray& ray, const BVH& original);
};

class BVH4 {
    BVH4(bvhvec4slice verts) {
       const BVH original{verts};
       bvh.ConvertFrom(original);
    }
    int Intersect(Ray& ray) {
        return bvh.Intesect(Ray& ray, original);
    }
     
 private:
     BVH original;
     BVH4 bvh;
};
```

The term `view` isn't great here, since it has its own data, just not the ones from original. That might be a lot of duplicated code to do that on all types, but at least:
* There is a super simple code path for user that just want to get started
* There is a more advanced code path for user that need to convert/rebuild multiple times

**Comment by DavidPeicho** [comment]
Just a side note, I have almost finished wrapping the library in Rust, and for now I have something like that:

```rust
let bvh  = BVH::new(&triangles);
let bvh4 = BVH4::new(&bvh);

let mut ray: Ray = Ray::new([0.0, 0.0, 0.0], [0.0, 0.0, -1.0]);
assert_eq!(bvh4.intersect(&mut ray), 1);
assert_relative_eq!(ray.hit.t, f32::MAX);

let mut ray: Ray = Ray::new([-1.5, 0.5, 0.0], [0.0, 0.0, -1.0]);
assert_eq!(bvh4.intersect(&mut ray), 2);
assert_relative_eq!(ray.hit.t, 1.0);
assert_eq!(ray.hit.prim, 0);

let mut ray: Ray = Ray::new([1.5, 0.45, 0.0], [0.0, 0.0, -1.0]);
assert_eq!(bvh4.intersect(&mut ray), 2);
assert_relative_eq!(ray.hit.t, 1.0);
assert_eq!(ray.hit.prim, 1);
```

I kept the design as close as possible to what you have done. Positive side effect of the lifetime checking in rust, is that I can't drop `bvh` without first dropping `bvh4`.

**Comment by jbikker** [comment]
Reopening this to improve visibility.
I dabbled in Rust for a while (worked at Traverse Research) so I fully appreciate how ownership would be far less of an issue in that language... I highly appreciate your efforts to get proper ownership in the C++ api.

````
class BVH4 {
  ...     
 private:
     BVH original;
     BVH4 bvh;
};
````

This is great, imo. They must both exist so we keep them together, like in the original API, but far less convoluted. 

Here it is fully clear that the original BVH is needed for the existence of a BVH4. We can probably add a comment to ````BVH original```` that says 'member because bvh relies on its data', to point out to the curious developer why we chose this construct. We could then add the ```Update```` method that your mentioned earlier to update the BVH4 in cases were we made deliberate changes to the original bvh, e.g. rebuilding or refitting.

That does mean that the data members should probably be public, at least BVH original, so it can be targetted with ````::Refit````, ````::Build````.

In this scheme, layout ````BVH_Verbose```` may need to become hidden. It's use is mainly for ````::Optimize````, and it is used in a flow where we convert ````BVH```` to ````BVH_Verbose````, then optimize, then convert back. We could add verbose as a private class to BVH and have Optimize as a method in BVH.

**Comment by DavidPeicho** [comment]
We just need to pin a naming I guess for the BVHs that aren't "standalone", so this part:

```cpp
class BVH4 {
  ...     
 private:
     BVH original;
     BVH4 bvh; // This
};
```

> That does mean that the data members should probably be public, at least BVH original, so it can be targetted with ::Refit, ::Build.

Definitely. However if we do that, the sub bvh also needs to be updated, so that should probably be on `BVH4`?
So turns out all those BVHs will still require `Build` and `Refit`

**Comment by jbikker** [comment]
I pushed some changes to dev. It works out quite nicely; to obtain a ````BVH4_CPU```` you simply instantiate it, then ````Build```` it. Changing the ````BVH```` to ````BVH_SoA```` is now a change to a single line. See tiny_bvh_pt for an example. And, tiny_bvh_minimal remains unchanged; you can still use the default BVH, build it and call ````Intersect```` on it.

All BVH classes now have these same three methods:

````
Build
Intersect
IsOccluded
````

Plan is now to complete this with ````Refit````.

Note that I still don't really use class derivation, so the calls are not virtual function calls. Despite that the common functionality is useful in source code, obviously.

One challenge that remains is 'Verbose', which is needed for compacting and optimization. There is currently no convenient way to build a ````BVH4_CPU```` over an optimized BVH, because the construction of that BVH has become implicit. It can still be done, because you can construct a ````BHV4_CPU```` using an existing (and optimized, if you wish) ````BVH````, but that re-introduces the ownership problems we set out to solve. Maybe that is ok for now, for users that don't mind reading the manual. ;)

This week I want to switch to building a wavefront GPU path tracer to put some basis under the use case of tinybvh and attract some more support. We need some eye candy. ;)

**Comment by DavidPeicho** [comment]
I think it's nice. I feel however that one API will not work now:

```cpp
BVH bvh;
BVH8 bvh8;
bvh8::ConvertFrom(original);
// `bvh8.bvh` is empty.
```

I still think there is a second path missing, basically one where the original `BVH` isn't owned. Could be something as simple as just asserting in all methods requiring the original `bvh` to be built, and a second set of methods for external `bvh`? I don't mind trying to tackle that especially if you are busy with the GPU pathtracer. Also relates to the `Verbose` issue I feel.

BTW my initial goal to port this library in Rust was indeed to replace my own bvh implementation in [Albedo](https://github.com/albedo-engine/albedo). So if the new API works well enough in Rust, maybe I can finish the integration in the pathtracer as well and that's another example for this library!

**Comment by jbikker** [comment]
Well to some extent this already works. For the TRAVERSE_4WAY_OPTIMIZED experiment in speedtest, the following sequence is used:

````
bvh4 = new BVH4( *bvh );
bvh4_cpu = new BVH4_CPU( *bvh4 );
````

This starts with an optimized bvh. This is turned into a bvh4, which keeps a copy of the optimized bvh, without owning it. bvh4_cpu does the same in turn and grabs a copy of the bvh4 to produce the final format, bvh4_cpu.

I think it's not very pretty though, and: I can't get it to work with instances instead of pointers. Move constructors and the like elude me and the related r-values seem a bit... repulsive. ;)

**Comment by DavidPeicho** [comment]
Not sure to exactly understand the problem here. I actually think it's pretty :D I mean, if we could nicely show in the API that the second one requires the first one, would be awesome.

What's the issue here with move ctor? I use them extensively maybe I can help

**Comment by jbikker** [comment]
Haha, ok. :) Inside that constructor, all it does is copy 'original' to 'bvh', then do the ConvertFrom.  Alternatively, we could move the copy of original to bvh to the ConvertFrom itself and delete that particular constructor. Then the flow becomes:

````
bvh4.ConvertFrom( bvh );
bvh4_cpu.ConvertFrom( bvh4 );
````

That's assuming everything is an instance now, obviously. I think that is in fact super pretty. :) This also re-enables the Verbose format, and allows for proper Optimize plus whatever else we come up with in the future. Simple API if you want simple stuff, flexible otherwise. 

So we're done?

**Comment by DavidPeicho** [comment]
I am not sure I follow everything I would need to see more code to understand. But I think we could still have two code paths, one that fully owns, and one that doesn't:

```cpp
bvh4.ConvertFrom(std::move(bvh)); // Here it's clear that accessing `bvh` after is evil
bvh4.Intersect(ray); // Owned

bvh4.ConvertFrom(bvh);
bvh4.Intersect(bvh, ray); // Not Owned
```

Might be a little confusing but if we assert properly in all methods it should be fine.

In any cayse, this can absolutely come later. It's quite possible that nobody re-use an original BVH contrary to what we were thinking originally :D

**Comment by DavidPeicho** [comment]
I think the dev branch has a bug tho, the BVH4 build has `triCount`=`2` for the root node.

**Comment by jbikker** [comment]
That is odd, speedtest runs fine and so does tiny_bvh_pt here, both in gcc and msvc. Which project are you running?

**Comment by DavidPeicho** [comment]
I am using `BVH4`, not `BVH4_CPU`, maybe that could be related? I guess if `BVH4` was broken, then `BVH4_CPU` would be tho hehe.

It's in my tests in the rust library. It worked before I upgraded to the changes from yesterday/today. It could also be totally a mistake on me :)

**Comment by DavidPeicho** [comment]
Was a bug on my side, but I do get different number of `nodes` built for `BVH4` on Ubuntu vs MacOS. Not sure how that could be on my side, but who knows.

**Comment by jbikker** [comment]
Fp32 math results vary; there's accuracy problems, order of operations, fma
and so on. On x86, when using the dedicated fpu registers, math isn't even
deterministic... I do hope the sah cost of the.produced trees is at least
similar?

**Comment by DavidPeicho** [comment]
Yeah that makes sense, just think it's funny I get 2 vs 4 nodes. There isn't any `SAHCost` on `BVH4`, probably need to expose that for more layouts

**Comment by DavidPeicho** [comment]
Actually found the reason: https://github.com/jbikker/tinybvh/issues/61

**Comment by jbikker** [comment]
Closing this one for now, we can continue with the others. :)
