### ISSUE TITLE
Crashes with CWBVH usage

### ISSUE THREAD

**Issue by andr3wmac** [jbikker/tinybvh#67]
When I build a CWBVH it crashes because allocatedBlocks is uninitialized so its value can be greater than spaceNeeded and no allocation of bvh8Data/bvh8Tris occurs. 

Second problem is when I create a BVH8 and then build a CWBVH by using ConvertFrom when I go to free them, freeing both results in a crash. At first glance it looks like this is because the copy of BVH8 is not a deep copy so its two structs holding the same pointer to bvh8Node and then it gets freed twice when bvh8 is destructed.

**Comment by jbikker** [comment]
This should be fixed in the latest commit on the dev branch, can you verify? The data was indeed not zeroed. Regarding the second problem: I am not sure what you encountered, perhaps it is related to the first issue; The CWBVH is not using data from bvh8, since it needs a specific format for both nodes and tris.

**Comment by jbikker** [comment]
Second issue was actually an issue too, sorry for dismissing that too soon. This should now be resolved: tinybvh now keeps track of ownership of bvhs and prevents duplicated deletion.

**Comment by andr3wmac** [comment]
Np, just tested the latest and it looks like everyone is working great 👍 thanks for the quick fixes.
